### ISSUE TITLE
Improve next and previous buttons behavior

### ISSUE THREAD

**Issue by rafaelleru** [rafaelleru/torrent-player#23]

**Comment by abhishek1nair** [comment]
@rafaelleru what improvements are you looking for? UI or functionality?

**Comment by rafaelleru** [comment]
Currently both buttons are working fine, but if you like you can implement the fast play or replay by a long press in this buttons. @abhishek1nair

**Comment by abhishek1nair** [comment]
@rafaelleru thanks will take this up
