### ISSUE TITLE
Drag torrent files support 

### ISSUE THREAD

**Issue by rafaelleru** [rafaelleru/torrent-player#30]

**Comment by onaralili** [comment]
I forked the project, however, cannot run, it returns error
 _Cannot find module 'vuedraggable'_

**Comment by rafaelleru** [comment]
Did you install all the dependencies??

**Comment by onaralili** [comment]
@rafaelleru yep, to make sure i did it twice :)

**Comment by rafaelleru** [comment]
It's weird can you please run npm i vuedraggable?

**Comment by onaralili** [comment]
@rafaelleru oh, it seems to work, it is weird that it is not being installed when I run _npm install_
