### ISSUE TITLE
keybindings to control music playing

### ISSUE THREAD

**Issue by rafaelleru** [rafaelleru/torrent-player#32]

**Comment by niralpokal** [comment]
If you want I can help with this.

**Comment by rafaelleru** [comment]
shure!! go ahead!! 😄 @niralpokal

**Comment by niralpokal** [comment]
Is there a list of which keys will control which part, or a general description on what you are looking for?

**Comment by rafaelleru** [comment]
Just like other players like spotify or vld:
- space play/pause
- Crtl+right-arrow next song
- Ctrl+left-arrow prev song
and all the things you like.

**Comment by rafaelleru** [comment]
@niralpokal see #34 I think keyevents should be controlled in the main process
