### ISSUE TITLE
make songlist to be reorderable 

### ISSUE THREAD

**Issue by rafaelleru** [rafaelleru/torrent-player#35]
https://github.com/SortableJS/Vue.Draggable

**Comment by pthomas931** [comment]
@rafaelleru Which song list are you referring to?

**Comment by rafaelleru** [comment]
when you add some torrents, all the files from the torrent are displayed in a songList.vue component, you can run the project and try it yourself 😄

**Comment by rafaelleru** [comment]
closed on b936931
