### ISSUE TITLE
CSS error

### ISSUE THREAD

**Issue by rafaelleru** [rafaelleru/torrent-player#37]
all the a tags are getting properties from vue-material css and breaking all our css.

**Comment by abhanshgiri21** [comment]
could you be a little more descriptive, i would love to help with this issue.

**Comment by rafaelleru** [comment]
For some reason the title and songs titles are displayed in a pink color from vue-material theme 
![image](https://user-images.githubusercontent.com/6851409/31862645-9a593ce8-b741-11e7-9f03-aa2219623370.png)

Just like the photo, before of this strange behaivor the TorrentPlayer title and buttons were withe and the songs titles black.

**Comment by abhanshgiri21** [comment]
by title you mean the "Torrent Player" written on  blue background ?
and i cannot see any song title in above image!

**Comment by rafaelleru** [comment]
Yes it is.
To view the song list run the program and load some torrent files.

**Comment by darshanjayadev** [comment]
It can be fixed by adding a CSS file and targeting title with an ID to address the CSS specificity issue.

**Comment by abhanshgiri21** [comment]
i am doing it right now.

**Comment by rafaelleru** [comment]
closes by ce8e2eaa23af64b27518dcd42e2c821732e1d2fb
